name: Node.js CI

on:
  release:
    types: [published]

jobs:
  depoly:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set yarn version
        run: |
          corepack enable
          yarn set version stable

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Upload production-ready build files
        run: yarn deploy:server
        env: # Or as an environment variable
          DEPLOY_SSH_PORT: ${{ secrets.DEPLOY_SSH_PORT }}
          DEPLOY_SSH_USERNAME: ${{ secrets.DEPLOY_SSH_USERNAME }}
          DEPLOY_SSH_PASSWORD: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          DEPLOY_SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
